<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['code' => 'AD', 'code3' => 'AND', 'name' => 'Andorra', 'number' => '020', 'stdcode' => '+376'],
            ['code' => 'AE', 'code3' => 'ARE', 'name' => 'United Arab Emirates (the)', 'number' => '784', 'stdcode' => '+971'],
            ['code' => 'AF', 'code3' => 'AFG', 'name' => 'Afghanistan', 'number' => '004', 'stdcode' => '+93'],
            ['code' => 'AG', 'code3' => 'ATG', 'name' => 'Antigua and Barbuda', 'number' => '028', 'stdcode' => '+1-268'],
            ['code' => 'AI', 'code3' => 'AIA', 'name' => 'Anguilla', 'number' => '660', 'stdcode' => '+1-264'],
            ['code' => 'AL', 'code3' => 'ALB', 'name' => 'Albania', 'number' => '008', 'stdcode' => '+355'],
            ['code' => 'AM', 'code3' => 'ARM', 'name' => 'Armenia', 'number' => '051', 'stdcode' => '+374'],
            ['code' => 'AO', 'code3' => 'AGO', 'name' => 'Angola', 'number' => '024', 'stdcode' => '+244'],
            ['code' => 'AR', 'code3' => 'ARG', 'name' => 'Argentina', 'number' => '032', 'stdcode' => '+54'],
            ['code' => 'AS', 'code3' => 'ASM', 'name' => 'American Samoa', 'number' => '016', 'stdcode' => '+1-684'],
            ['code' => 'AT', 'code3' => 'AUT', 'name' => 'Austria', 'number' => '040', 'stdcode' => '+43'],
            ['code' => 'AU', 'code3' => 'AUS', 'name' => 'Australia', 'number' => '036', 'stdcode' => '+61'],
            ['code' => 'AW', 'code3' => 'ABW', 'name' => 'Aruba', 'number' => '533', 'stdcode' => '+297'],
            ['code' => 'AX', 'code3' => 'ALA', 'name' => 'Åland Islands', 'number' => '248', 'stdcode' => '+358-18'],
            ['code' => 'AZ', 'code3' => 'AZE', 'name' => 'Azerbaijan', 'number' => '031', 'stdcode' => '+994'],
            ['code' => 'BA', 'code3' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'number' => '070', 'stdcode' => '+387'],
            ['code' => 'BB', 'code3' => 'BRB', 'name' => 'Barbados', 'number' => '052', 'stdcode' => '+1-246'],
            ['code' => 'BD', 'code3' => 'BGD', 'name' => 'Bangladesh', 'number' => '050', 'stdcode' => '+880'],
            ['code' => 'BE', 'code3' => 'BEL', 'name' => 'Belgium', 'number' => '056', 'stdcode' => '+32'],
            ['code' => 'BF', 'code3' => 'BFA', 'name' => 'Burkina Faso', 'number' => '854', 'stdcode' => '+226'],
            ['code' => 'BG', 'code3' => 'BGR', 'name' => 'Bulgaria', 'number' => '100', 'stdcode' => '+359'],
            ['code' => 'BH', 'code3' => 'BHR', 'name' => 'Bahrain', 'number' => '048', 'stdcode' => '+973'],
            ['code' => 'BI', 'code3' => 'BDI', 'name' => 'Burundi', 'number' => '108', 'stdcode' => '+257'],
            ['code' => 'BJ', 'code3' => 'BEN', 'name' => 'Benin', 'number' => '204', 'stdcode' => '+229'],
            ['code' => 'BL', 'code3' => 'BLM', 'name' => 'Saint Barthélemy', 'number' => '652', 'stdcode' => '+590'],
            ['code' => 'BM', 'code3' => 'BMU', 'name' => 'Bermuda', 'number' => '060', 'stdcode' => '+1-441'],
            ['code' => 'BN', 'code3' => 'BRN', 'name' => 'Brunei Darussalam', 'number' => '096', 'stdcode' => '+673'],
            ['code' => 'BO', 'code3' => 'BOL', 'name' => 'Bolivia (Plurinational State of)', 'number' => '068', 'stdcode' => '+591'],
            ['code' => 'BQ', 'code3' => 'BES', 'name' => 'Bonaire, Sint Eustatius and Saba', 'number' => '535', 'stdcode' => '+599'],
            ['code' => 'BR', 'code3' => 'BRA', 'name' => 'Brazil', 'number' => '076', 'stdcode' => '+55'],
            ['code' => 'BS', 'code3' => 'BHS', 'name' => 'Bahamas (the)', 'number' => '044', 'stdcode' => '+1-242'],
            ['code' => 'BT', 'code3' => 'BTN', 'name' => 'Bhutan', 'number' => '064', 'stdcode' => '+975'],
            ['code' => 'BV', 'code3' => 'BVT', 'name' => 'Bouvet Island', 'number' => '074', 'stdcode' => '+47'],
            ['code' => 'BW', 'code3' => 'BWA', 'name' => 'Botswana', 'number' => '072', 'stdcode' => '+267'],
            ['code' => 'BY', 'code3' => 'BLR', 'name' => 'Belarus', 'number' => '112', 'stdcode' => '+375'],
            ['code' => 'BZ', 'code3' => 'BLZ', 'name' => 'Belize', 'number' => '084', 'stdcode' => '+501'],
            ['code' => 'CA', 'code3' => 'CAN', 'name' => 'Canada', 'number' => '124', 'stdcode' => '+1'],
            ['code' => 'CC', 'code3' => 'CCK', 'name' => 'Cocos (Keeling) Islands (the)', 'number' => '166', 'stdcode' => '+61'],
            ['code' => 'CD', 'code3' => 'COD', 'name' => 'Congo (the Democratic Republic of the)', 'number' => '180', 'stdcode' => '+243'],
            ['code' => 'CF', 'code3' => 'CAF', 'name' => 'Central African Republic (the)', 'number' => '140', 'stdcode' => '+236'],
            ['code' => 'CG', 'code3' => 'COG', 'name' => 'Congo (the)', 'number' => '178', 'stdcode' => '+242'],
            ['code' => 'CH', 'code3' => 'CHE', 'name' => 'Switzerland', 'number' => '756', 'stdcode' => '+41'],
            ['code' => 'CI', 'code3' => 'CIV', 'name' => 'Côte d\'Ivoire', 'number' => '384', 'stdcode' => '+225'],
            ['code' => 'CK', 'code3' => 'COK', 'name' => 'Cook Islands (the)', 'number' => '184', 'stdcode' => '+682'],
            ['code' => 'CL', 'code3' => 'CHL', 'name' => 'Chile', 'number' => '152', 'stdcode' => '+56'],
            ['code' => 'CM', 'code3' => 'CMR', 'name' => 'Cameroon', 'number' => '120', 'stdcode' => '+237'],
            ['code' => 'CN', 'code3' => 'CHN', 'name' => 'China', 'number' => '156', 'stdcode' => '+86'],
            ['code' => 'CO', 'code3' => 'COL', 'name' => 'Colombia', 'number' => '170', 'stdcode' => '+57'],
            ['code' => 'CR', 'code3' => 'CRI', 'name' => 'Costa Rica', 'number' => '188', 'stdcode' => '+506'],
            ['code' => 'CU', 'code3' => 'CUB', 'name' => 'Cuba', 'number' => '192', 'stdcode' => '+53'],
            ['code' => 'CV', 'code3' => 'CPV', 'name' => 'Cabo Verde', 'number' => '132', 'stdcode' => '+238'],
            ['code' => 'CW', 'code3' => 'CUW', 'name' => 'Curaçao', 'number' => '531', 'stdcode' => '+599'],
            ['code' => 'CX', 'code3' => 'CXR', 'name' => 'Christmas Island', 'number' => '162', 'stdcode' => '+61'],
            ['code' => 'CY', 'code3' => 'CYP', 'name' => 'Cyprus', 'number' => '196', 'stdcode' => '+357'],
            ['code' => 'CZ', 'code3' => 'CZE', 'name' => 'Czechia', 'number' => '203', 'stdcode' => '+420'],
            ['code' => 'DE', 'code3' => 'DEU', 'name' => 'Germany', 'number' => '276', 'stdcode' => '+49'],
            ['code' => 'DJ', 'code3' => 'DJI', 'name' => 'Djibouti', 'number' => '262', 'stdcode' => '+253'],
            ['code' => 'DK', 'code3' => 'DNK', 'name' => 'Denmark', 'number' => '208', 'stdcode' => '+45'],
            ['code' => 'DM', 'code3' => 'DMA', 'name' => 'Dominica', 'number' => '212', 'stdcode' => '+1-767'],
            ['code' => 'DO', 'code3' => 'DOM', 'name' => 'Dominican Republic (the)', 'number' => '214', 'stdcode' => '+1-809'],
            ['code' => 'DZ', 'code3' => 'DZA', 'name' => 'Algeria', 'number' => '012', 'stdcode' => '+213'],
            ['code' => 'EC', 'code3' => 'ECU', 'name' => 'Ecuador', 'number' => '218', 'stdcode' => '+593'],
            ['code' => 'EE', 'code3' => 'EST', 'name' => 'Estonia', 'number' => '233', 'stdcode' => '+372'],
            ['code' => 'EG', 'code3' => 'EGY', 'name' => 'Egypt', 'number' => '818', 'stdcode' => '+20'],
            ['code' => 'EH', 'code3' => 'ESH', 'name' => 'Western Sahara', 'number' => '732', 'stdcode' => '+212'],
            ['code' => 'ER', 'code3' => 'ERI', 'name' => 'Eritrea', 'number' => '232', 'stdcode' => '+291'],
            ['code' => 'ES', 'code3' => 'ESP', 'name' => 'Spain', 'number' => '724', 'stdcode' => '+34'],
            ['code' => 'ET', 'code3' => 'ETH', 'name' => 'Ethiopia', 'number' => '231', 'stdcode' => '+251'],
            ['code' => 'FI', 'code3' => 'FIN', 'name' => 'Finland', 'number' => '246', 'stdcode' => '+358'],
            ['code' => 'FJ', 'code3' => 'FJI', 'name' => 'Fiji', 'number' => '242', 'stdcode' => '+679'],
            ['code' => 'FM', 'code3' => 'FSM', 'name' => 'Micronesia (Federated States of)', 'number' => '583', 'stdcode' => '+691'],
            ['code' => 'FO', 'code3' => 'FRO', 'name' => 'Faroe Islands (the)', 'number' => '234', 'stdcode' => '+298'],
            ['code' => 'FR', 'code3' => 'FRA', 'name' => 'France', 'number' => '250', 'stdcode' => '+33'],
            ['code' => 'GA', 'code3' => 'GAB', 'name' => 'Gabon', 'number' => '266', 'stdcode' => '+241'],
            ['code' => 'GB', 'code3' => 'GBR', 'name' => 'United Kingdom of Great Britain and Northern Ireland (the)', 'number' => '826', 'stdcode' => '+44'],
            ['code' => 'GD', 'code3' => 'GRD', 'name' => 'Grenada', 'number' => '308', 'stdcode' => '+1-473'],
            ['code' => 'GE', 'code3' => 'GEO', 'name' => 'Georgia', 'number' => '268', 'stdcode' => '+995'],
            ['code' => 'GF', 'code3' => 'GUF', 'name' => 'French Guiana', 'number' => '254', 'stdcode' => '+594'],
            ['code' => 'GG', 'code3' => 'GGY', 'name' => 'Guernsey', 'number' => '831', 'stdcode' => '+44-1481'],
            ['code' => 'GH', 'code3' => 'GHA', 'name' => 'Ghana', 'number' => '288', 'stdcode' => '+233'],
            ['code' => 'GI', 'code3' => 'GIB', 'name' => 'Gibraltar', 'number' => '292', 'stdcode' => '+350'],
            ['code' => 'GL', 'code3' => 'GRL', 'name' => 'Greenland', 'number' => '304', 'stdcode' => '+299'],
            ['code' => 'GM', 'code3' => 'GMB', 'name' => 'Gambia (the)', 'number' => '270', 'stdcode' => '+220'],
            ['code' => 'GN', 'code3' => 'GIN', 'name' => 'Guinea', 'number' => '324', 'stdcode' => '+224'],
            ['code' => 'GP', 'code3' => 'GLP', 'name' => 'Guadeloupe', 'number' => '312', 'stdcode' => '+590'],
            ['code' => 'GQ', 'code3' => 'GNQ', 'name' => 'Equatorial Guinea', 'number' => '226', 'stdcode' => '+240'],
            ['code' => 'GR', 'code3' => 'GRC', 'name' => 'Greece', 'number' => '300', 'stdcode' => '+30'],
            ['code' => 'GT', 'code3' => 'GTM', 'name' => 'Guatemala', 'number' => '320', 'stdcode' => '+502'],
            ['code' => 'GU', 'code3' => 'GUM', 'name' => 'Guam', 'number' => '316', 'stdcode' => '+1-671'],
            ['code' => 'GW', 'code3' => 'GNB', 'name' => 'Guinea-Bissau', 'number' => '624', 'stdcode' => '+245'],
            ['code' => 'GY', 'code3' => 'GUY', 'name' => 'Guyana', 'number' => '328', 'stdcode' => '+592'],
            ['code' => 'HK', 'code3' => 'HKG', 'name' => 'Hong Kong', 'number' => '344', 'stdcode' => '+852'],
            ['code' => 'HM', 'code3' => 'HMD', 'name' => 'Heard Island and McDonald Islands', 'number' => '334', 'stdcode' => '+61'],
            ['code' => 'HN', 'code3' => 'HND', 'name' => 'Honduras', 'number' => '340', 'stdcode' => '+504'],
            ['code' => 'HR', 'code3' => 'HRV', 'name' => 'Croatia', 'number' => '191', 'stdcode' => '+385'],
            ['code' => 'HT', 'code3' => 'HTI', 'name' => 'Haiti', 'number' => '332', 'stdcode' => '+509'],
            ['code' => 'HU', 'code3' => 'HUN', 'name' => 'Hungary', 'number' => '348', 'stdcode' => '+36'],
            ['code' => 'ID', 'code3' => 'IDN', 'name' => 'Indonesia', 'number' => '360', 'stdcode' => '+62'],
            ['code' => 'IE', 'code3' => 'IRL', 'name' => 'Ireland', 'number' => '372', 'stdcode' => '+353'],
            ['code' => 'IL', 'code3' => 'ISR', 'name' => 'Israel', 'number' => '376', 'stdcode' => '+972'],
            ['code' => 'IM', 'code3' => 'IMN', 'name' => 'Isle of Man', 'number' => '833', 'stdcode' => '+44-1624'],
            ['code' => 'IN', 'code3' => 'IND', 'name' => 'India', 'number' => '356', 'stdcode' => '+91'],
            ['code' => 'IO', 'code3' => 'IOT', 'name' => 'British Indian Ocean Territory (the)', 'number' => '086', 'stdcode' => '+246'],
            ['code' => 'IQ', 'code3' => 'IRQ', 'name' => 'Iraq', 'number' => '368', 'stdcode' => '+964'],
            ['code' => 'IR', 'code3' => 'IRN', 'name' => 'Iran (Islamic Republic of)', 'number' => '364', 'stdcode' => '+98'],
            ['code' => 'IS', 'code3' => 'ISL', 'name' => 'Iceland', 'number' => '352', 'stdcode' => '+354'],
            ['code' => 'IT', 'code3' => 'ITA', 'name' => 'Italy', 'number' => '380', 'stdcode' => '+39'],
            ['code' => 'JE', 'code3' => 'JEY', 'name' => 'Jersey', 'number' => '832', 'stdcode' => '+44-1534'],
            ['code' => 'JM', 'code3' => 'JAM', 'name' => 'Jamaica', 'number' => '388', 'stdcode' => '+1-876'],
            ['code' => 'JO', 'code3' => 'JOR', 'name' => 'Jordan', 'number' => '400', 'stdcode' => '+962'],
            ['code' => 'JP', 'code3' => 'JPN', 'name' => 'Japan', 'number' => '392', 'stdcode' => '+81'],
            ['code' => 'KE', 'code3' => 'KEN', 'name' => 'Kenya', 'number' => '404', 'stdcode' => '+254'],
            ['code' => 'KG', 'code3' => 'KGZ', 'name' => 'Kyrgyzstan', 'number' => '417', 'stdcode' => '+996'],
            ['code' => 'KH', 'code3' => 'KHM', 'name' => 'Cambodia', 'number' => '116', 'stdcode' => '+855'],
            ['code' => 'KI', 'code3' => 'KIR', 'name' => 'Kiribati', 'number' => '296', 'stdcode' => '+686'],
            ['code' => 'KM', 'code3' => 'COM', 'name' => 'Comoros (the)', 'number' => '174', 'stdcode' => '+269'],
            ['code' => 'KN', 'code3' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'number' => '659', 'stdcode' => '+1-869'],
            ['code' => 'KP', 'code3' => 'PRK', 'name' => 'Korea (the Democratic People\'s Republic of)', 'number' => '408', 'stdcode' => '+850'],
            ['code' => 'KR', 'code3' => 'KOR', 'name' => 'Korea (the Republic of)', 'number' => '410', 'stdcode' => '+82'],
            ['code' => 'KW', 'code3' => 'KWT', 'name' => 'Kuwait', 'number' => '414', 'stdcode' => '+965'],
            ['code' => 'KY', 'code3' => 'CYM', 'name' => 'Cayman Islands (the)', 'number' => '136', 'stdcode' => '+1-345'],
            ['code' => 'KZ', 'code3' => 'KAZ', 'name' => 'Kazakhstan', 'number' => '398', 'stdcode' => '+7'],
            ['code' => 'LA', 'code3' => 'LAO', 'name' => 'Lao People\'s Democratic Republic (the)', 'number' => '418', 'stdcode' => '+856'],
            ['code' => 'LB', 'code3' => 'LBN', 'name' => 'Lebanon', 'number' => '422', 'stdcode' => '+961'],
            ['code' => 'LC', 'code3' => 'LCA', 'name' => 'Saint Lucia', 'number' => '662', 'stdcode' => '+1-758'],
            ['code' => 'LI', 'code3' => 'LIE', 'name' => 'Liechtenstein', 'number' => '438', 'stdcode' => '+423'],
            ['code' => 'LK', 'code3' => 'LKA', 'name' => 'Sri Lanka', 'number' => '144', 'stdcode' => '+94'],
            ['code' => 'LR', 'code3' => 'LBR', 'name' => 'Liberia', 'number' => '430', 'stdcode' => '+231'],
            ['code' => 'LS', 'code3' => 'LSO', 'name' => 'Lesotho', 'number' => '426', 'stdcode' => '+266'],
            ['code' => 'LT', 'code3' => 'LTU', 'name' => 'Lithuania', 'number' => '440', 'stdcode' => '+370'],
            ['code' => 'LU', 'code3' => 'LUX', 'name' => 'Luxembourg', 'number' => '442', 'stdcode' => '+352'],
            ['code' => 'LV', 'code3' => 'LVA', 'name' => 'Latvia', 'number' => '428', 'stdcode' => '+371'],
            ['code' => 'LY', 'code3' => 'LBY', 'name' => 'Libya', 'number' => '434', 'stdcode' => '+218'],
            ['code' => 'MA', 'code3' => 'MAR', 'name' => 'Morocco', 'number' => '504', 'stdcode' => '+212'],
            ['code' => 'MC', 'code3' => 'MCO', 'name' => 'Monaco', 'number' => '492', 'stdcode' => '+377'],
            ['code' => 'MD', 'code3' => 'MDA', 'name' => 'Moldova (the Republic of)', 'number' => '498', 'stdcode' => '+373'],
            ['code' => 'ME', 'code3' => 'MNE', 'name' => 'Montenegro', 'number' => '499', 'stdcode' => '+382'],
            ['code' => 'MG', 'code3' => 'MDG', 'name' => 'Madagascar', 'number' => '450', 'stdcode' => '+261'],
            ['code' => 'MH', 'code3' => 'MHL', 'name' => 'Marshall Islands (the)', 'number' => '584', 'stdcode' => '+692'],
            ['code' => 'MK', 'code3' => 'MKD', 'name' => 'North Macedonia', 'number' => '807', 'stdcode' => '+389'],
            ['code' => 'ML', 'code3' => 'MLI', 'name' => 'Mali', 'number' => ' Mali', 'stdcode' => '+223'],
            ['code' => 'MM', 'code3' => 'MMR', 'name' => 'Myanmar', 'number' => '104', 'stdcode' => '+95'],
            ['code' => 'MN', 'code3' => 'MNG', 'name' => 'Mongolia', 'number' => '496', 'stdcode' => '+976'],
            ['code' => 'MO', 'code3' => 'MAC', 'name' => 'Macao', 'number' => '446', 'stdcode' => '+853'],
            ['code' => 'MP', 'code3' => 'MNP', 'name' => 'Northern Mariana Islands (the)', 'number' => '580', 'stdcode' => '+1-670'],
            ['code' => 'MQ', 'code3' => 'MTQ', 'name' => 'Martinique', 'number' => '474', 'stdcode' => '+596'],
            ['code' => 'MR', 'code3' => 'MRT', 'name' => 'Mauritania', 'number' => '478', 'stdcode' => '+222'],
            ['code' => 'MS', 'code3' => 'MSR', 'name' => 'Montserrat', 'number' => '500', 'stdcode' => '+1-664'],
            ['code' => 'MT', 'code3' => 'MLT', 'name' => 'Malta', 'number' => '470', 'stdcode' => '+356'],
            ['code' => 'MU', 'code3' => 'MUS', 'name' => 'Mauritius', 'number' => '480', 'stdcode' => '+230'],
            ['code' => 'MV', 'code3' => 'MDV', 'name' => 'Maldives', 'number' => '462', 'stdcode' => '+960'],
            ['code' => 'MW', 'code3' => 'MWI', 'name' => 'Malawi', 'number' => '454', 'stdcode' => '+265'],
            ['code' => 'MX', 'code3' => 'MEX', 'name' => 'Mexico', 'number' => '484', 'stdcode' => '+52'],
            ['code' => 'MY', 'code3' => 'MYS', 'name' => 'Malaysia', 'number' => '458', 'stdcode' => '+60'],
            ['code' => 'MZ', 'code3' => 'MOZ', 'name' => 'Mozambique', 'number' => '508', 'stdcode' => '+258'],
            ['code' => 'NA', 'code3' => 'NAM', 'name' => 'Namibia', 'number' => '516', 'stdcode' => '+264'],
            ['code' => 'NC', 'code3' => 'NCL', 'name' => 'New Caledonia', 'number' => '540', 'stdcode' => '+687'],
            ['code' => 'NE', 'code3' => 'NER', 'name' => 'Niger (the)', 'number' => '562', 'stdcode' => '+227'],
            ['code' => 'NF', 'code3' => 'NFK', 'name' => 'Norfolk Island', 'number' => '574', 'stdcode' => '+672'],
            ['code' => 'NG', 'code3' => 'NGA', 'name' => 'Nigeria', 'number' => '566', 'stdcode' => '+234'],
            ['code' => 'NI', 'code3' => 'NIC', 'name' => 'Nicaragua', 'number' => '558', 'stdcode' => '+505'],
            ['code' => 'NL', 'code3' => 'NLD', 'name' => 'Netherlands (the)', 'number' => '528', 'stdcode' => '+31'],
            ['code' => 'NO', 'code3' => 'NOR', 'name' => 'Norway', 'number' => '578', 'stdcode' => '+47'],
            ['code' => 'NP', 'code3' => 'NPL', 'name' => 'Nepal', 'number' => '524', 'stdcode' => '+977'],
            ['code' => 'NR', 'code3' => 'NRU', 'name' => 'Nauru', 'number' => '520', 'stdcode' => '+674'],
            ['code' => 'NU', 'code3' => 'NIU', 'name' => 'Niue', 'number' => '570', 'stdcode' => '+683'],
            ['code' => 'NZ', 'code3' => 'NZL', 'name' => 'New Zealand', 'number' => '554', 'stdcode' => '+64'],
            ['code' => 'OM', 'code3' => 'OMN', 'name' => 'Oman', 'number' => '512', 'stdcode' => '+968'],
            ['code' => 'PA', 'code3' => 'PAN', 'name' => 'Panama', 'number' => '591', 'stdcode' => '+507'],
            ['code' => 'PE', 'code3' => 'PER', 'name' => 'Peru', 'number' => '604', 'stdcode' => '+51'],
            ['code' => 'PF', 'code3' => 'PYF', 'name' => 'French Polynesia', 'number' => '258', 'stdcode' => '+689'],
            ['code' => 'PG', 'code3' => 'PNG', 'name' => 'Papua New Guinea', 'number' => '598', 'stdcode' => '+675'],
            ['code' => 'PH', 'code3' => 'PHL', 'name' => 'Philippines (the)', 'number' => '608', 'stdcode' => '+63'],
            ['code' => 'PK', 'code3' => 'PAK', 'name' => 'Pakistan', 'number' => '586', 'stdcode' => '+92'],
            ['code' => 'PL', 'code3' => 'POL', 'name' => 'Poland', 'number' => '616', 'stdcode' => '+48'],
            ['code' => 'PM', 'code3' => 'SPM', 'name' => 'Saint Pierre and Miquelon', 'number' => '666', 'stdcode' => '+508'],
            ['code' => 'PN', 'code3' => 'PCN', 'name' => 'Pitcairn', 'number' => '612', 'stdcode' => '+64'],
            ['code' => 'PR', 'code3' => 'PRI', 'name' => 'Puerto Rico', 'number' => '630', 'stdcode' => '+1-787'],
            ['code' => 'PT', 'code3' => 'PRT', 'name' => 'Portugal', 'number' => '620', 'stdcode' => '+351'],
            ['code' => 'PW', 'code3' => 'PLW', 'name' => 'Palau', 'number' => '585', 'stdcode' => '+680'],
            ['code' => 'PY', 'code3' => 'PRY', 'name' => 'Paraguay', 'number' => '600', 'stdcode' => '+595'],
            ['code' => 'QA', 'code3' => 'QAT', 'name' => 'Qatar', 'number' => '634', 'stdcode' => '+974'],
            ['code' => 'RE', 'code3' => 'REU', 'name' => 'Réunion', 'number' => '638', 'stdcode' => '+262'],
            ['code' => 'RO', 'code3' => 'ROU', 'name' => 'Romania', 'number' => '642', 'stdcode' => '+40'],
            ['code' => 'RS', 'code3' => 'SRB', 'name' => 'Serbia', 'number' => '688', 'stdcode' => '+381'],
            ['code' => 'RU', 'code3' => 'RUS', 'name' => 'Russian Federation (the)', 'number' => '643', 'stdcode' => '+7'],
            ['code' => 'RW', 'code3' => 'RWA', 'name' => 'Rwanda', 'number' => '646', 'stdcode' => '+250'],
            ['code' => 'SA', 'code3' => 'SAU', 'name' => 'Saudi Arabia', 'number' => '682', 'stdcode' => '+966'],
            ['code' => 'SB', 'code3' => 'SLB', 'name' => 'Solomon Islands', 'number' => '090', 'stdcode' => '+677'],
            ['code' => 'SC', 'code3' => 'SYC', 'name' => 'Seychelles', 'number' => '690', 'stdcode' => '+248'],
            ['code' => 'SD', 'code3' => 'SDN', 'name' => 'Sudan (the)', 'number' => '729', 'stdcode' => '+249'],
            ['code' => 'SE', 'code3' => 'SWE', 'name' => 'Sweden', 'number' => '752', 'stdcode' => '+46'],
            ['code' => 'SG', 'code3' => 'SGP', 'name' => 'Singapore', 'number' => '702', 'stdcode' => '+65'],
            ['code' => 'SH', 'code3' => 'SHN', 'name' => 'Saint Helena', 'number' => '654', 'stdcode' => '+290'],
            ['code' => 'SI', 'code3' => 'SVN', 'name' => 'Slovenia', 'number' => '705', 'stdcode' => '+386'],
            ['code' => 'SJ', 'code3' => 'SJM', 'name' => 'Svalbard and Jan Mayen', 'number' => '744', 'stdcode' => '+47'],
            ['code' => 'SK', 'code3' => 'SVK', 'name' => 'Slovakia', 'number' => '703', 'stdcode' => '+421'],
            ['code' => 'SL', 'code3' => 'SLE', 'name' => 'Sierra Leone', 'number' => '694', 'stdcode' => '+232'],
            ['code' => 'SM', 'code3' => 'SMR', 'name' => 'San Marino', 'number' => '674', 'stdcode' => '+378'],
            ['code' => 'SN', 'code3' => 'SEN', 'name' => 'Senegal', 'number' => '686', 'stdcode' => '+221'],
            ['code' => 'SO', 'code3' => 'SOM', 'name' => 'Somalia', 'number' => '706', 'stdcode' => '+252'],
            ['code' => 'SR', 'code3' => 'SUR', 'name' => 'Suriname', 'number' => '740', 'stdcode' => '+597'],
            ['code' => 'SS', 'code3' => 'SSD', 'name' => 'South Sudan', 'number' => '728', 'stdcode' => '+211'],
            ['code' => 'ST', 'code3' => 'STP', 'name' => 'Sao Tome and Principe', 'number' => '678', 'stdcode' => '+239'],
            ['code' => 'SV', 'code3' => 'SLV', 'name' => 'El Salvador', 'number' => '222', 'stdcode' => '+503'],
            ['code' => 'SX', 'code3' => 'SXM', 'name' => 'Sint Maarten (Dutch part)', 'number' => '534', 'stdcode' => '+1-721'],
            ['code' => 'SY', 'code3' => 'SYR', 'name' => 'Syrian Arab Republic', 'number' => '760', 'stdcode' => '+963'],
            ['code' => 'SZ', 'code3' => 'SWZ', 'name' => 'Eswatini', 'number' => '748', 'stdcode' => '+268'],
            ['code' => 'TC', 'code3' => 'TCA', 'name' => 'Turks and Caicos Islands (the)', 'number' => '796', 'stdcode' => '+1-649'],
            ['code' => 'TD', 'code3' => 'TCD', 'name' => 'Chad', 'number' => '148', 'stdcode' => '+235'],
            ['code' => 'TF', 'code3' => 'ATF', 'name' => 'French Southern Territories (the)', 'number' => '260', 'stdcode' => '+262'],
            ['code' => 'TG', 'code3' => 'TGO', 'name' => 'Togo', 'number' => '768', 'stdcode' => '+228'],
            ['code' => 'TH', 'code3' => 'THA', 'name' => 'Thailand', 'number' => '764', 'stdcode' => '+66'],
            ['code' => 'TJ', 'code3' => 'TJK', 'name' => 'Tajikistan', 'number' => '762', 'stdcode' => '+992'],
            ['code' => 'TK', 'code3' => 'TKL', 'name' => 'Tokelau', 'number' => '772', 'stdcode' => '+690'],
            ['code' => 'TL', 'code3' => 'TLS', 'name' => 'Timor-Leste', 'number' => '626', 'stdcode' => '+670'],
            ['code' => 'TM', 'code3' => 'TKM', 'name' => 'Turkmenistan', 'number' => '795', 'stdcode' => '+993'],
            ['code' => 'TN', 'code3' => 'TUN', 'name' => 'Tunisia', 'number' => '788', 'stdcode' => '+216'],
            ['code' => 'TO', 'code3' => 'TON', 'name' => 'Tonga', 'number' => '776', 'stdcode' => '+676'],
            ['code' => 'TR', 'code3' => 'TUR', 'name' => 'Turkey', 'number' => '792', 'stdcode' => '+90'],
            ['code' => 'TT', 'code3' => 'TTO', 'name' => 'Trinidad and Tobago', 'number' => '780', 'stdcode' => '+1-868'],
            ['code' => 'TV', 'code3' => 'TUV', 'name' => 'Tuvalu', 'number' => '798', 'stdcode' => '+688'],
            ['code' => 'TZ', 'code3' => 'TZA', 'name' => 'Tanzania, the United Republic of', 'number' => '834', 'stdcode' => '+255'],
            ['code' => 'UA', 'code3' => 'UKR', 'name' => 'Ukraine', 'number' => '804', 'stdcode' => '+380'],
            ['code' => 'UG', 'code3' => 'UGA', 'name' => 'Uganda', 'number' => '800', 'stdcode' => '+256'],
            ['code' => 'UM', 'code3' => 'UMI', 'name' => 'United States Minor Outlying Islands', 'number' => '581', 'stdcode' => '+1'],
            ['code' => 'US', 'code3' => 'USA', 'name' => 'United States of America (the)', 'number' => '840', 'stdcode' => '+1'],
            ['code' => 'UY', 'code3' => 'URY', 'name' => 'Uruguay', 'number' => '858', 'stdcode' => '+598'],
            ['code' => 'UZ', 'code3' => 'UZB', 'name' => 'Uzbekistan', 'number' => '860', 'stdcode' => '+998'],
            ['code' => 'VA', 'code3' => 'VAT', 'name' => 'Holy See (the)', 'number' => '336', 'stdcode' => '+379'],
            ['code' => 'VC', 'code3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'number' => '670', 'stdcode' => '+1-784'],
            ['code' => 'VE', 'code3' => 'VEN', 'name' => 'Venezuela (Bolivarian Republic of)', 'number' => '862', 'stdcode' => '+58'],
            ['code' => 'VG', 'code3' => 'VGB', 'name' => 'Virgin Islands (British)', 'number' => '092', 'stdcode' => '+1-284'],
            ['code' => 'VI', 'code3' => 'VIR', 'name' => 'Virgin Islands (U.S.)', 'number' => '850', 'stdcode' => '+1-340'],
            ['code' => 'VN', 'code3' => 'VNM', 'name' => 'Viet Nam', 'number' => '704', 'stdcode' => '+84'],
            ['code' => 'VU', 'code3' => 'VUT', 'name' => 'Vanuatu', 'number' => '548', 'stdcode' => '+678'],
            ['code' => 'WF', 'code3' => 'WLF', 'name' => 'Wallis and Futuna', 'number' => '876', 'stdcode' => '+681'],
            ['code' => 'WS', 'code3' => 'WSM', 'name' => 'Samoa', 'number' => '882', 'stdcode' => '+685'],
            ['code' => 'YE', 'code3' => 'YEM', 'name' => 'Yemen', 'number' => '887', 'stdcode' => '+967'],
            ['code' => 'YT', 'code3' => 'MYT', 'name' => 'Mayotte', 'number' => '175', 'stdcode' => '+262'],
            ['code' => 'ZA', 'code3' => 'ZAF', 'name' => 'South Africa', 'number' => '710', 'stdcode' => '+27'],
            ['code' => 'ZM', 'code3' => 'ZMB', 'name' => 'Zambia', 'number' => '894', 'stdcode' => '+260'],
            ['code' => 'ZW', 'code3' => 'ZWE', 'name' => 'Zimbabwe', 'number' => '716', 'stdcode' => '+263']
        ];

        $data = [];
        foreach ($countries as $country) {
            $data[] = [
                'code' => $country['code'],
                'code3' => $country['code3'],
                'name' => $country['name'],
                'number' => $country['number'],
                'stdcode' => $country['stdcode'],
            ];
        }
        
        DB::table('countries')->insert($data);
    }
}
